---
title: "Econ 330: Urban Economics"
subtitle: "Lecture 3"
author: "John Morehouse"
date: "January 14th, 2020"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, center, middle

```{R, setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(
  broom, here, tidyverse,
  latex2exp, ggplot2, ggthemes, viridis, extrafont, gridExtra,
  kableExtra,
  dplyr, magrittr, knitr, parallel, tufte,emo
)
# Define pink color
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
# Dark slate grey: #314f4f
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F
)
opts_chunk$set(dev = "svg")
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
# A blank theme for ggplot
theme_empty <- theme_bw() + theme(
  line = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  plot.margin = structure(c(0, 0, -0.5, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_simple <- theme_bw() + theme(
  line = element_blank(),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text.x = element_text(size = 18, family = "STIXGeneral"),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  # plot.margin = structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_math <- theme_void() + theme(
  text = element_text(family = "MathJax_Math"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_serif <- theme_void() + theme(
  text = element_text(family = "MathJax_Main"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes <- theme_void() + theme(
  text = element_text(family = "Fira Sans Book"),
  axis.title = element_text(size = 18),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
```



# Lecture III: Existence of Cities

---




name: schedule

# Schedule

## Today

--

1) .hi.purple[Data & History]

2) .hi.purple[Why do Cities exist?]

3) .hi.purple[Introduction to Clustering]


--

--

## Upcoming

  - .hi.slate[Letter of Intro on Canvas] 

  - .hi.slate[Reading] (Chapter II & III _ToTC_)
  
  - .hi.slate[HW 1] (due on Jan 23rd)

--

---






#About HWI

HW I will be posted after class (tonight or tomorrow morning)

- Due on .hi.orange[Jan 23rd] at the __start of class__

--

- HW I _looks_ very long. I want to give everyone sufficient space to write their answers

- Majority of questions are from this week. One question from lecture 5 (next tuesday)

--

--

## Important

  - Print the assignment and turn it in on what you print out
  
  - Use scratch paper first if needed. __Points will be deducted for messy work__
  
  - __Staple your work__

--

---




name: data
#Most People Live in Cities

<iframe src="https://ourworldindata.org/grapher/urban-and-rural-population?time=2017" style="width: 100%; height: 100%; border: 0px none;"></iframe>

---


#A Global Phenomena

<iframe src="https://ourworldindata.org/grapher/share-of-population-urban" style="width: 100%; height: 100%; border: 0px none;"></iframe>

---



#And it is pretty recent

<iframe src="https://ourworldindata.org/grapher/urbanization-last-500-years?time=2016" style="width: 100%; height: 600px; border: 0px none;"></iframe>

---

name: history
#A Brief History Lesson
##Claim

Over the last few hundred years the world _has become_ .hi.purple[flat]



---



#A Brief History Lesson


##Claim

Over the last few hundred years the world _has become_ .hi.purple[flat]


---


name: paradox
#A Paradox


.qa[Q]: What is the .hi.orange[paradox] between the things I have just discussed?






---







class: inverse, middle
# Checklist

.col-left[
1) .hi[Data & History] `r emo::ji("check")`



2) .hi.purple[Why do Cities exist?]
]

.col-right[

3) .hi.purple[Introduction to Clustering]

]

---




name: exist
# Why do Cities Exist?

What do you think? .hi.purple[Discuss]

--

This question has a pretty simple answer. What is it?

--

<center>
<font size="15"> Trade </font>
</center>

--

<center>
<font size="15"> with a few caveats... </font>
</center>

--


Suppose there was .hi[no trade]. What would we need for this to be true? _Would this lead to no cities?_



---




name: trade
# No Cities

--

1) No differences in .hi[productivity] of __land__ _or_ __labor__


--

--


2) Constant Returns to Scale (CRS) in .hi[Exchange] & transportation

--


--

--

3) CRS in .hi.orange[Production]

--


--

---

#Implications?

1. __No exchange__

  - Everybody is equally productive and all land is the same

2. __No cities__

  - Dense living is costly (higher land prices). No benefit

---

# Relax Assumption 1

.hi.purple[Question]: Is all land and labor equally productive? 


--


--

---


# Back to 201

##Reminder:


  - .hi.slate[Absolute Advantage] (AA): An economic agent or entity has .hi.purple[AA] in exchange if they can produce more of the good in the same amount of time 
  
      - or the same amount of the good in less time
 
--
 
  - .hi.slate[Comparative Advantage] (CA) : An economic agent or entity has .hi[CA] in exchange if they can produce the good at a lower _oppurtunity cost_

--

--

.hi.slate[Production Possibilities Frontier] (PPF): All possible combinations of goods that an economic agent or entity can produce

--

---

# PPF's

.hi.slate[Example]: 

  - Suppose we have two countries, A & B. They are producing guns and oil
  
Each counties PPF is .note[given] by:

- .hi[County A]: $\color{#e64173} {Guns_A = 10 - 2*Oil_A}$

- .hi[County B]: $\color{#6A5ACD} {Guns_B = 20 - 5*Oil_B}$


--

1) Graph each countries PPF

2) Determine who has the AA in each good and who has the CA in each good

--

---

#PPF's

```{R, ppf, echo = F, fig.height = 5, fig.width = 8, dev = "svg"}
county_one <- function(x) 10-2*x
county_two <- function(x) 20-5*x
ggplot(data.frame(x=c(0, 10)), aes(x)) + 
  stat_function(fun=county_one, col = red_pink)+
  geom_vline(xintercept =0, size = 0.5)+
  geom_hline(yintercept =0, size = 0.5)+
  ggthemes::theme_pander()+
  ylim(0,22)+
  geom_text(x=0, y=10, label="Country A")+
  labs(x = "Oil", y = "Guns")


```
---

#PPF's

```{R, ppf2, echo = F, fig.height = 5, fig.width = 8, dev = "svg"}
county_one <- function(x) 10-2*x
county_two <- function(x) 20-5*x
ggplot(data.frame(x=c(0, 10)), aes(x)) + 
  stat_function(fun=county_one, col = red_pink)+
  stat_function(fun=county_two, col = "purple")+
  geom_vline(xintercept =0, size = 0.5)+
  geom_hline(yintercept =0, size = 0.5)+
  ggthemes::theme_pander()+
  ylim(0,22)+
  geom_text(x=0, y=10, label="Country A")+
  geom_text(x=0, y = 20, label="Country B")+
  labs(x = "Oil", y = "Guns")


```
---


# PPF Heuristics

When looking at PPF's, to determine:


1) .hi.purple[AA]: Check .hi[intercepts]
  
  - Whoever has higher - valued .hi[intercept] has the .hi.purple[AA] in production of that good


2) .hi.purple[CA]: Check .hi.orange[slopes]

  - A __steeper__ .hi.orange[slope] indicates .hi.purple[CA] on the vertical axis
  
  - A __shallower__ .hi.orange[slope] indicates .hi.purple[CA] on the horizontal axis

---




# Relax Assumption 2

In absence of scale economies, households trade directly<sup>.hi[†]</sup>


.footnote[
.hi[†] Scale economies: _bigger_ $\rightarrow$ _cheaper per unit_

]

--

- .hi[Scale economies]: trading firm's are beneficial

- Workers do not like commuting $\implies$ they live close to firm

  - .hi.purple[Land prices] are bid up
  
- Higher price of land increases density  $\implies$ city!

--
---

name: factory
# Relax Assumption 3

Suppose we do not have CRS

  - This means the cost per unit of production changes as quantity changes

--

##Example

Consider a shirt making factory


--

  
--

--

---


#Factory Towns

Under what condition will a consumer purchase the shirt from a factory over home?


--

.qa[Questions]:

1. Graph the cost of shirts throughout the entire region

2. Find the .hi.orange[market area] of the town

--

  - Find the .hi.orange[maximum distances] to the east and west that consumers will purchase the shirt from the factory
--

--

---

#Regional Costs

---

#Market Area Calculation

Market area depends on which side we are looking at. Let $m$ denote miles



---


# Factory Towns

1) Would workers rather live .hi.orange[closer] or .hi[further] from the factory?
  
--
  

--

2) What happens to land-prices .hi[close] to the factory?

--
  

--

3)ith What happens to .hi[density]?

--


--

---






class: inverse, middle
# Checklist

.col-left[

1) .hi[Data & History] `r emo::ji("check")`


2) .hi[Why do Cities exist?] `r emo::ji("check")`



]

.col-right[
3) .hi.purple[Introduction to Clustering]
]

---





# Clustering

So we explained _why_ cities exist. Can we explain their size?

- Let's start by asking why firms cluster. Where to start? __Axiom 5__

--

__Axiom 5__: .hi[_Competition generates zero economic profit_]

--


- If a firm is making positive economic profit, more firms enter the market

- What happens to the profit per firm as more firms enter?

--

- It decreases. Eventually goes to zero

--

---

name: zero_profit
#Example

How many firms are in the cluster?

```{R, cluster_graph, echo = F, fig.height = 5, fig.width = 8, dev = "svg"}
profit = function(x) -x^3+5*x^2

  #create cluster plot
ggplot(data.frame(x=c(0, 6)), aes(x)) + 
  stat_function(fun=profit, col = "purple")+
  geom_vline(xintercept =0, size = 0.5)+
  geom_hline(yintercept =0, size = 0.5)+
  ggthemes::theme_pander()+
  xlim(0,6)+
  ylim(-20,20)+
  labs(x = "Number of Firms\nIn Cluster", y = "Profit Per Firm")


```


---





class: inverse, middle
# Checklist

.col-left[

1) .hi[Data & History] `r emo::ji("check")`



2) .hi[Why do Cities exist?] `r emo::ji("check")`

 
  
]

.col-right[

3) .hi[Introduction to Clustering] `r emo::ji("check")`


]
---








#Table of Contents

.col-left[
###Data & History
.smallest[
1. [Urban Populations](#data)
1. [History](#history)
1. [Paradox](#paradox)
]


###Existence
.smallest[

1. [Why do Cities Exist?](#exist)
1. [Trade Basics](#trade)
1. [Factory Towns](#factory_towns)

]
]

.col-right[
##Clustering
1. [Zero Profit](#zero_profit)
.smallest[

]
]


---



exclude: true 
```{r decktape}
p_load(pagedown)
pagedown::chrome_print(here::here("003-size","slides_canvas","lecture_three.html"))
```



<!-- --- -->
<!-- exclude: true -->

<!-- ```{R, generate pdfs, include = F} -->
<!-- system("decktape remark 02_goodsmarket_part1.html 02_goodsmarket_part1.pdf --chrome-arg=--allow-file-access-from-files") -->
<!-- ``` -->








